logging:
  level:
    ROOT: DEBUG
    com.project.planner: DEBUG

spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5442/postgres
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/master.yml
    url: jdbc:postgresql://localhost:5442/postgres
    user: postgres
    password: postgres
    drop-first: true

server:
  port: 8081

application:
  security:
    authentication:
      base64-secret: asd
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800